/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maps;

import javax.swing.JOptionPane;

/**
 *
 * @author shahe
 */
public class TruthToMap3 extends javax.swing.JFrame {

    /**
     * Creates new form TruthToMap3
     */
    public TruthToMap3() {
        initComponents();
        setLocationRelativeTo(rootPane);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER PARAMTERS ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("A");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("B");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("C");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("F(A, B, C)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("1");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("1");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("0");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("1");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("1");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("0");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("0");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("1");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("1");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("0");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("1");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("0");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("1");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("0");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("1");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("0");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("1");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        jTextField7.setText("jTextField7");

        jTextField8.setText("jTextField8");

        jButton1.setText("DERIVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField4)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jTextField8))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14)
                    .addComponent(jLabel22)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15)
                    .addComponent(jLabel23)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16)
                    .addComponent(jLabel24)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17)
                    .addComponent(jLabel25)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18)
                    .addComponent(jLabel26)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19)
                    .addComponent(jLabel27)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel20)
                    .addComponent(jLabel28)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel21)
                    .addComponent(jLabel29)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
new Kmap2().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int a = Integer.parseInt(jTextField1.getText());
int b = Integer.parseInt(jTextField2.getText());
int c = Integer.parseInt(jTextField3.getText());
int d = Integer.parseInt(jTextField4.getText());
int e = Integer.parseInt(jTextField5.getText());
int f = Integer.parseInt(jTextField6.getText());
int g = Integer.parseInt(jTextField7.getText());
int h = Integer.parseInt(jTextField8.getText());

if (a!=0 && b==0 && c==0 && d==0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "1 \t 0 \t 0 \t 0 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'B'C'", "Boolean Function", 1);
}
if (a==0 && b!=0 && c==0 && d==0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 1 \t 0 \t 0 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'B'C", "Boolean Function", 1);
}
if (a==0 && b==0 && c!=0 && d==0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 1 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'BC'", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d!=0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 1 \t 0 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'BC", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e!=0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 1 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = AB'C'", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e==0 && f!=0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 0 \t 1 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = AB'C", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e==0 && f==0 && g!=0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 0 \t 0 \t 0 \t 1", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = ABC'", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e==0 && f==0 && g==0 && h!=0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 0 \t 0 \t 1 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = ABC", "Boolean Function", 1);
}

//=============================================================================================================
//end of single block checks
//=============================================================================================================

if (a!=0 && b!=0 && c==0 && d==0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "1 \t 1 \t 0 \t 0 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'B'", "Boolean Function", 1);
}
if (a!=0 && b==0 && c==0 && d==0 && e!=0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "1 \t 0 \t 0 \t 0 \n 1 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = B'C'", "Boolean Function", 1);
}
if (a==0 && b!=0 && c==0 && d==0 && e==0 && f!=0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 1 \t 0 \t 0 \n 0 \t 1 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = B'C", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d!=0 && e==0 && f==0 && g==0 && h!=0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 1 \t 0 \n 0 \t 0 \t 1 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = BC", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 1 \n 0 \t 0 \t 0 \t 1", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = BC'", "Boolean Function", 1);
}
if (a!=0 && b!=0 && c!=0 && d!=0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "1 \t 1 \t 1 \t 1 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e!=0 && f!=0 && g!=0 && h!=0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 1 \t 1 \t 1 \t 1", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A", "Boolean Function", 1);
}
if (a==0 && b==0 && c!=0 && d!=0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 1 \t 1 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'B", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e!=0 && f!=0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 1 \t 1 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = AB'", "Boolean Function", 1);
}
if (a!=0 && b!=0 && c==0 && d==0 && e==0 && f==0 && g!=0 && h!=0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 0 \t 0 \t 1 \t 1", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = AB", "Boolean Function", 1);
}
if (a==0 && b!=0 && c==0 && d!=0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 1 \t 1 \t 0 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'C", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e==0 && f!=0 && g==0 && h!=0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 0 \t 1 \t 1 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = AC", "Boolean Function", 1);
}
if (a!=0 && b!=0 && c==0 && d!=0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "1 \t 1 \t 1 \t 0 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'B' + A'BC", "Boolean Function", 1);
}
if (a==0 && b!=0 && c!=0 && d!=0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 1 \t 1 \t 1 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'B'C + A'B", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 1 \t 1 \t 1 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = AB'C' + AC", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e==0 && f!=0 && g!=0 && h!=0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 0 \t 1 \t 1 \t 1", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = AB'C + AB", "Boolean Function", 1);
}
if (a!=0 && b==0 && c!=0 && d==0 && e==0 && f==0 && g==0 && h==0){
    JOptionPane.showMessageDialog(null, "1 \t 0 \t 0 \t 1 \n 0 \t 0 \t 0 \t 0", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = A'C'", "Boolean Function", 1);
}
if (a==0 && b==0 && c==0 && d==0 && e!=0 && f==0 && g!=0 && h==0){
    JOptionPane.showMessageDialog(null, "0 \t 0 \t 0 \t 0 \n 1 \t 0 \t 0 \t 1", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = AC'", "Boolean Function", 1);
}
if (a!=0 && b==0 && c!=0 && d==0 && e!=0 && f==0 && g!=0 && h==0){
    JOptionPane.showMessageDialog(null, "1 \t 0 \t  \t 1 \n 1 \t 0 \t 0 \t 1", "3 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "F(A, B, C) = C'", "Boolean Function", 1);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TruthToMap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TruthToMap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TruthToMap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TruthToMap3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TruthToMap3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
