/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maps;

import javax.swing.JOptionPane;

/**
 *
 * @author shahe
 */
public class twoVBool extends javax.swing.JFrame {

    /**
     * Creates new form twoVBool
     */
    public twoVBool() {
        initComponents();
        setLocationRelativeTo(rootPane);
        
        jTextField1.setText("");
        jTextField2.setText("");
        
        //developing stage for more than 2 inputs
        jTextField3.setText("");
        jTextField3.disable();
        
        jTextField4.setText("");
        jTextField4.disable();
        
        jTextField5.setText("");
        jTextField5.disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER A BOOLEAN FUNCTION");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField1.setText("jTextField1");

        jButton1.setText("DERIVE TRUTH TABLE AND K-MAP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("+");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("+");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("+");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("+");

        jLabel2.setText("Enter First Term of Equation");

        jLabel7.setText("Enter Second Term of Equation");

        jLabel8.setText("Enter Third Term of Equation");

        jLabel9.setText("Enter Forth Term of Equation");

        jLabel10.setText("Enter Fifith Term of Equation");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("USE A AND B FOR VARIABLES");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(jButton1)))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField5)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String a = jTextField1.getText();String b = jTextField2.getText();String c = jTextField3.getText();String d = jTextField4.getText();String e = jTextField5.getText();
String sep1, sep2;
int ans1,ans2,ans3,ans4;

if (a.equalsIgnoreCase("A") && b.equalsIgnoreCase("B")){
    sep1 = a;    sep2 = b;
    ans1 = 0 + 0;
    ans2 = 0 + 1;
    ans3 = 1 + 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB") && b.equalsIgnoreCase("A")){
    sep1 = a; sep2 = b;
    ans1 = 0 + 0;
    ans2 = 0 + 0;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB") && b.equalsIgnoreCase("B")){
    sep1 = a; sep2 = b;
    ans1 = 0;
    ans2 = 1;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB") && b.equalsIgnoreCase("AB")){
    sep1 = a; sep2 = b;
    ans1 = 0;
    ans2 = 0;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A") && b.equalsIgnoreCase("AB")){
    ans1 = 0;
    ans2 = 0;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("B") && b.equalsIgnoreCase("AB")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
//=================================================================================================================================================================
//BASICS DONE
//ADDING NOT GATES HERE
//=================================================================================================================================================================
if (a.equalsIgnoreCase("A'") && b.equalsIgnoreCase("B")){
    ans1 = 1;
    ans2 = 1;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A") && b.equalsIgnoreCase("B'")){
    ans1 = 1;
    ans2 = 0;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B") && b.equalsIgnoreCase("A")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB'") && b.equalsIgnoreCase("A")){
    ans1 = 0;
    ans2 = 0;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B'") && b.equals("A")){
    ans1 = 1;
    ans2 = 0;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B") && b.equalsIgnoreCase("B")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB'") && b.equalsIgnoreCase("B")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B'") && b.equalsIgnoreCase("B")){
    ans1 = 1;
    ans2 = 1;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A") && b.equalsIgnoreCase("A'B")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A") && b.equalsIgnoreCase("AB'")){
    ans1 = 0;
    ans2 = 0;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A") && b.equalsIgnoreCase("A'B'")){
    ans1 = 1;
    ans2 = 0;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("B") && b.equalsIgnoreCase("A'B")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("B") && b.equalsIgnoreCase("AB'")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("B") && b.equalsIgnoreCase("A'B'")){
    ans1 = 1;
    ans2 = 1;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
//======================================================================================================================================================
//End of not statements
//Start of couble statements
//======================================================================================================================================================
if (a.equalsIgnoreCase("AB") && b.equalsIgnoreCase("AB")){
    ans1 = 0;
    ans2 = 0;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B") && b.equalsIgnoreCase("AB")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB'") && b.equalsIgnoreCase("AB")){
    ans1 = 0;
    ans2 = 0;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}

if (a.equalsIgnoreCase("A'B'") && b.equalsIgnoreCase("AB")){
    ans1 = 1;
    ans2 = 0;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB") && b.equalsIgnoreCase("A'B")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B") && b.equalsIgnoreCase("A'B")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 0;
    ans4 = 0;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB'") && b.equalsIgnoreCase("A'B")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 1;
    ans4 = 0;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B'") && b.equalsIgnoreCase("A'B")){
    ans1 = 1;
    ans2 = 1;
    ans3 = 0;
    ans4 = 0;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB") && b.equalsIgnoreCase("AB'")){
    ans1 = 0;
    ans2 = 0;
    ans3 = 1;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B") && b.equalsIgnoreCase("AB'")){
    ans1 = 0;
    ans2 = 1;
    ans3 = 1;
    ans4 = 0;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB'") && b.equalsIgnoreCase("AB'")){
    ans1 = 0;
    ans2 = 0;
    ans3 = 1;
    ans4 = 0;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B'") && b.equalsIgnoreCase("AB'")){
    ans1 = 1;
    ans2 = 0;
    ans3 = 1;
    ans4 = 0;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB") && b.equalsIgnoreCase("A'B'")){
    ans1 = 1;
    ans2 = 0;
    ans3 = 0;
    ans4 = 1;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B") && b.equalsIgnoreCase("A'B'")){
    ans1 = 1;
    ans2 = 1;
    ans3 = 0;
    ans4 = 0;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("AB'") && b.equalsIgnoreCase("A'B'")){
    ans1 = 1;
    ans2 = 0;
    ans3 = 1;
    ans4 = 0;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
if (a.equalsIgnoreCase("A'B'") && b.equalsIgnoreCase("A'B'")){
    ans1 = 1;
    ans2 = 0;
    ans3 = 0;
    ans4 = 0;
    
    JOptionPane.showMessageDialog(null, ans1+"\t"+ans2+"\n"+ans3+"\t"+ans4, "2 Variable K-Map", 1);
    JOptionPane.showMessageDialog(null, "A \t B \t F(A, B) \n 0 \t 0 \t\t"+ans1+"\n 0 \t 1 \t\t "+ans2+"\n 1 \t 0 \t\t"+ans3+"\n 1 \t 1 \t\t"+ans4);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
new Kmap2().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(twoVBool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(twoVBool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(twoVBool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(twoVBool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new twoVBool().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
